changelog:
  exclude:
    labels:
      - kind:test
      - kind:ci
  categories:
    - title: Breaking Changes
      labels:
        - compat:breaking
    - title: New features and enhancements
      labels:
        - kind:feat
    - title: Fixed issues
      labels:
        - kind:fix
    - title: Documentation
      labels:
        - kind:doc
    - title: Other Changes
      labels:
        - '*'
